services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: payment-schedule-backend
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/payment_schedule
      QUARKUS_DATASOURCE_USERNAME: admin
      QUARKUS_DATASOURCE_PASSWORD: admin123
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_HTTP_CORS_ORIGINS: http://localhost:3000,http://localhost:80,http://frontend
    ports:
      - "9090:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health/ready" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:9090/api
    container_name: payment-schedule-frontend
    environment:
      - VITE_API_URL=http://localhost:9090/api
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
