FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0 
WORKDIR /work/

COPY build/*-runner /work/application
RUN chmod 0755 /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]